import {firebaseConfig} from './trip-data.js?v=salzburg-1';
import {countdown,escapeHTML as esc,safeLink,categories,statuses,mergeTickets,validateTicket} from './travel-extras-core.js?v=1';
function updateCountdown(){const d=countdown();document.querySelector('#departure-count').textContent=d.label;document.querySelector('#departure-message').textContent=d.message}
updateCountdown();setInterval(updateCountdown,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateCountdown()});
const grid=document.querySelector('#reservation-grid'),dialog=document.querySelector('#reservation-dialog'),form=document.querySelector('#reservation-form'),status=document.querySelector('#reservation-status'),formMessage=document.querySelector('#reservation-form-message'),retry=document.querySelector('#reservation-retry');
let tickets=mergeTickets([]),filter='전체',ready=false,pending=false,api,db,unsubscribe,editing=null,baseRevision=0,returnFocus=null;
const field=name=>form.elements.namedItem(name);
function message(text,error=false){status.textContent=text;status.dataset.error=String(error)}
function lock(){document.querySelectorAll('#reservation-add,#reservation-grid button,#reservation-form input,#reservation-form select,#reservation-form textarea,#reservation-save').forEach(el=>el.disabled=!ready||pending||!navigator.onLine);document.querySelector('#reservation-cancel').disabled=pending;document.querySelector('#reservation-close').disabled=pending}
function render(){
  const active=tickets.filter(t=>!t.deleted),shown=tickets.filter(t=>filter==='보관함'?t.deleted:!t.deleted&&(filter==='전체'||t.category===filter));
  document.querySelector('#reservation-summary').textContent=`${active.filter(t=>t.status==='예약 완료').length} / ${active.length}건 예약 완료`;
  grid.innerHTML=shown.length?shown.map(t=>`<article class="reservation-card" data-confirmed="${t.status==='예약 완료'}"><div class="reservation-card-head"><span>${esc(t.category)}</span><span class="reservation-badge">${t.deleted?'보관됨':esc(t.status)}</span></div><h3>${esc(t.title)}</h3><time class="reservation-date" datetime="${esc(t.date)}">${esc(t.date?.slice(5).replace('-','. ')||'날짜 미정')}</time><p class="reservation-details">${esc([t.time,t.place].filter(Boolean).join('\n'))}</p>${t.memo?`<p class="reservation-memo">${esc(t.memo)}</p>`:''}<div class="reservation-actions">${safeLink(t.url)?`<a href="${esc(safeLink(t.url))}" target="_blank" rel="noopener noreferrer">티켓 · 예약 열기 ↗</a>`:''}${t.deleted?`<button data-restore="${esc(t.id)}" type="button">다시 꺼내기</button>`:`<button data-edit="${esc(t.id)}" type="button" aria-label="${esc(t.title)} 예약 수정">${t.revision?'수정':'예약 정보 입력'}</button><button class="archive-button" data-archive="${esc(t.id)}" type="button" aria-label="${esc(t.title)} 보관함으로 이동">보관</button>`}</div></article>`).join(''):'<p class="reservation-empty">'+(filter==='보관함'?'보관한 예약이 없어요.':'이 분류에 등록한 예약이 없어요. 위의 예약 추가 버튼으로 적어보세요.')+'</p>';
  lock();
}
document.querySelector('#reservation-filters').innerHTML=['전체',...categories,'보관함'].map(x=>`<button type="button" data-filter="${x}" aria-pressed="${x==='전체'}">${x}</button>`).join('');
field('category').innerHTML=categories.map(x=>`<option>${x}</option>`).join('');field('status').innerHTML=statuses.map(x=>`<option>${x}</option>`).join('');
document.querySelector('#reservation-filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});
function openEditor(t,trigger){if(!ready||pending)return;returnFocus=trigger;editing=t?.id||api.doc(api.collection(db,'trips','europe-2026','tickets')).id;baseRevision=t?.revision||0;form.reset();formMessage.textContent='';document.querySelector('#reservation-dialog-title').textContent=t?'예약 정보 수정':'예약 추가';for(const name of ['category','title','date','time','place','status','url','memo'])field(name).value=t?.[name]??({category:'기타',date:'2026-11-13',status:'예약 전'}[name]||'');dialog.showModal();lock();field('title').focus()}
function closeEditor(){if(pending)return;dialog.close();const id=editing;editing=null;const next=Array.from(grid.querySelectorAll('[data-edit]')).find(b=>b.dataset.edit===id);(next||returnFocus||document.querySelector('#reservation-add'))?.focus()}
document.querySelector('#reservation-add').addEventListener('click',e=>openEditor(null,e.currentTarget));
document.querySelector('#reservation-close').addEventListener('click',closeEditor);document.querySelector('#reservation-cancel').addEventListener('click',closeEditor);dialog.addEventListener('cancel',e=>{e.preventDefault();closeEditor()});
async function saveTicket(id,data,expectedRevision){
  const ref=api.doc(db,'trips','europe-2026','tickets',id);
  await api.runTransaction(db,async tx=>{const old=await tx.get(ref);if((old.exists()?old.data().revision:0)!==expectedRevision)throw new Error('conflict');tx.set(ref,{...data,revision:expectedRevision+1,updatedAt:Date.now()})});
}
function saveError(e){return e?.message==='conflict'?'다른 사람이 먼저 수정했어요. 입력 내용은 남아 있어요. 닫고 최신 예약을 다시 열어 수정해 주세요.':'공유 저장에 실패했어요. 입력 내용은 남아 있어요. 연결을 확인하고 다시 저장해 주세요.'}
form.addEventListener('submit',async e=>{e.preventDefault();if(!ready||pending||!navigator.onLine||!form.reportValidity())return;const data=Object.fromEntries(['category','title','date','time','place','status','url','memo'].map(n=>[n,field(n).value.trim()]));if(!validateTicket(data)){formMessage.textContent='날짜와 링크를 확인해 주세요. 링크는 https:// 또는 http://로 시작해야 해요.';return}pending=true;formMessage.textContent='공유 저장 중…';lock();try{await saveTicket(editing,{...data,deleted:false},baseRevision);pending=false;closeEditor();message('공유 저장 완료 · 모두에게 반영됐어요')}catch(err){formMessage.textContent=saveError(err);message('예약 저장 실패 · 입력 내용을 확인해 주세요',true)}finally{pending=false;lock()}});
grid.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!ready||pending||!navigator.onLine)return;const id=b.dataset.edit||b.dataset.archive||b.dataset.restore,t=tickets.find(x=>x.id===id);if(!t)return;if(b.dataset.edit){openEditor(t,b);return}pending=true;lock();message('공유 저장 중…');const {id:ignored,revision,updatedAt,...data}=t;try{await saveTicket(id,{...data,deleted:!!b.dataset.archive},revision);message(b.dataset.archive?'보관함으로 옮겼어요. 보관함에서 다시 꺼낼 수 있어요.':'예약 목록으로 복원했어요.')}catch(err){message(saveError(err),true)}finally{pending=false;lock()}});
window.addEventListener('offline',()=>{message('인터넷 연결 끊김 · 마지막 예약 표시',true);lock()});window.addEventListener('online',()=>{ready=false;lock();connect()});
window.addEventListener('beforeunload',e=>{if(pending){e.preventDefault();e.returnValue=''}});
function connect(){if(!db)return;unsubscribe?.();ready=false;lock();message('공유 예약 불러오는 중…');unsubscribe=api.onSnapshot(api.collection(db,'trips','europe-2026','tickets'),{includeMetadataChanges:true},snapshot=>{tickets=mergeTickets(snapshot.docs.map(d=>({ ...d.data(),id:d.id})));ready=!snapshot.metadata.fromCache&&!snapshot.metadata.hasPendingWrites;render();retry.hidden=true;if(!pending)message(ready?'실시간 공유 중 · 예약 변경은 가족 모두에게 반영돼요':'공유 예약 연결 중 · 마지막 기록 표시')},()=>{ready=false;lock();message('공유 예약에 연결하지 못했어요. 연결을 다시 시도해 주세요.',true);retry.hidden=false})}
retry.addEventListener('click',()=>{if(db)connect();else location.reload()});render();
try{const [app,firestore]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);api=firestore;db=api.getFirestore(app.getApps().length?app.getApp():app.initializeApp(firebaseConfig));connect()}catch{message('공유 예약에 연결하지 못했어요. 인터넷 연결을 확인해 주세요.',true);retry.hidden=false}
